# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LightingKit Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LightingKit Example
  pod 'LightingKit', :git => 'https://github.com/p-morris/LightingKit'

end
